#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : openal-soft
Version  : 1.18.2
Release  : 17
URL      : http://www.openal-soft.org/openal-releases/openal-soft-1.18.2.tar.bz2
Source0  : http://www.openal-soft.org/openal-releases/openal-soft-1.18.2.tar.bz2
Summary  : OpenAL is a cross-platform 3D audio API
Group    : Development/Tools
License  : LGPL-2.0
Requires: openal-soft-bin
Requires: openal-soft-lib
Requires: openal-soft-data
BuildRequires : alsa-lib-dev
BuildRequires : alsa-lib-dev32
BuildRequires : cmake
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : pkgconfig(32libpulse)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pulseaudio-dev
BuildRequires : pulseaudio-dev32

%description
Source Install
==============
To install OpenAL Soft, use your favorite shell to go into the build/
directory, and run:

%package bin
Summary: bin components for the openal-soft package.
Group: Binaries
Requires: openal-soft-data

%description bin
bin components for the openal-soft package.


%package data
Summary: data components for the openal-soft package.
Group: Data

%description data
data components for the openal-soft package.


%package dev
Summary: dev components for the openal-soft package.
Group: Development
Requires: openal-soft-lib
Requires: openal-soft-bin
Requires: openal-soft-data
Provides: openal-soft-devel

%description dev
dev components for the openal-soft package.


%package dev32
Summary: dev32 components for the openal-soft package.
Group: Default
Requires: openal-soft-bin
Requires: openal-soft-data
Requires: openal-soft-dev

%description dev32
dev32 components for the openal-soft package.


%package lib
Summary: lib components for the openal-soft package.
Group: Libraries
Requires: openal-soft-data

%description lib
lib components for the openal-soft package.


%prep
%setup -q -n openal-soft-1.18.2
pushd ..
cp -a openal-soft-1.18.2 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1506360533
mkdir clr-build
pushd clr-build
cmake .. -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS:BOOL=ON -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DCMAKE_AR=/usr/bin/gcc-ar -DLIB_SUFFIX=64 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_RANLIB=/usr/bin/gcc-ranlib
make VERBOSE=1  %{?_smp_mflags}
popd
mkdir clr-build32
pushd clr-build32
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
cmake .. -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS:BOOL=ON -DLIB_INSTALL_DIR:PATH=/usr/lib32 -DCMAKE_AR=/usr/bin/gcc-ar -DLIB_SUFFIX=32 -DCMAKE_RANLIB=/usr/bin/gcc-ranlib
make VERBOSE=1  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1506360533
rm -rf %{buildroot}
pushd clr-build32
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
/usr/lib/cmake/OpenAL/OpenALConfig-relwithdebinfo.cmake
/usr/lib/cmake/OpenAL/OpenALConfig.cmake
/usr/lib64/cmake/OpenAL/OpenALConfig-relwithdebinfo.cmake
/usr/lib64/cmake/OpenAL/OpenALConfig.cmake

%files bin
%defattr(-,root,root,-)
/usr/bin/alrecord
/usr/bin/altonegen
/usr/bin/bsincgen
/usr/bin/makehrtf
/usr/bin/openal-info

%files data
%defattr(-,root,root,-)
/usr/share/openal/alsoftrc.sample
/usr/share/openal/hrtf/default-44100.mhr
/usr/share/openal/hrtf/default-48000.mhr
/usr/share/openal/presets/3D7.1.ambdec
/usr/share/openal/presets/hexagon.ambdec
/usr/share/openal/presets/itu5.1.ambdec
/usr/share/openal/presets/presets.txt
/usr/share/openal/presets/rectangle.ambdec
/usr/share/openal/presets/square.ambdec

%files dev
%defattr(-,root,root,-)
/usr/include/AL/al.h
/usr/include/AL/alc.h
/usr/include/AL/alext.h
/usr/include/AL/efx-creative.h
/usr/include/AL/efx-presets.h
/usr/include/AL/efx.h
/usr/lib/libopenal.so
/usr/lib64/libopenal.so
/usr/lib64/pkgconfig/openal.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/pkgconfig/32openal.pc
/usr/lib32/pkgconfig/openal.pc

%files lib
%defattr(-,root,root,-)
/usr/lib/libopenal.so.1
/usr/lib/libopenal.so.1.18.2
/usr/lib64/libopenal.so.1
/usr/lib64/libopenal.so.1.18.2
